name: "Aviator Signals"
description: "Upload the signals to Aviator."
branding:
  color: yellow
  icon: activity
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      filter: 'blob:none'

  - uses: actions/setup-python@v5
    with:
      python-version: "3.12"
      cache: "pip"

  - name: Install dependencies
    run: pip install requests
    shell: sh

  - name: Run uploader
    run: python $GITHUB_ACTION_PATH/action.py
    shell: sh
    env:
      GITHUB_SHA: ${{ github.sha }}
      REPO_NAME: ${{ github.repository }}
      AVIATOR_API_TOKEN: ${{ inputs.aviator-api-token }}
      INPUT_FORMAT: ${{ inputs.format }}
      FILE_PATHS: ${{ inputs.file-paths }}

inputs:
  aviator-api-token:
    description: "The Aviator API token"
    required: true
  file-paths:
    description: "The comma-separated glob paths to the input files"
    required: true
  format:
    description: "The format of the signals ('sarif' or 'astgrep')"
    required: false
    default: "sarif"
