name: "Aviator Signals"
description: "Runs linters and sends the output to aviator/api/signals."
branding:
  color: yellow
  icon: activity
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      filter: 'blob:none'

  # todo: only changed files?

  - uses: actions/setup-python@v5
    with:
      python-version: "3.12"
      cache: "pip"

  - name: Install linters
    run: |
      pip install pylint
      pip install mypy
    shell: sh

  - name: Setup reviewdog
    uses: reviewdog/action-setup@v1
    with:
      reviewdog_version: latest

  - name: Run linters
    run: python $GITHUB_ACTION_PATH/action.py path=$GITHUB_ACTION_PATH
    shell: sh

  # todo: update to check for 200 response, log response now for testing purposes
  - name: Upload Response Artifact
    uses: actions/upload-artifact@v3
    with:
      name: sarif_output
      path: sarif_output.json
env:
  ACTION_PATH: $GITHUB_ACTION_PATH