name: "Aviator Signals"
description: "Runs linters and sends the output to aviator/api/signals."
branding:
  color: yellow
  icon: activity
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      filter: 'blob:none'

  # todo: only changed files?

  - uses: actions/setup-python@v5
    with:
      python-version: "3.12"
      cache: "pip"

  - name: Install pylint
    run: |
      pip install pylint

  - name: Setup reviewdog
    uses: reviewdog/action-setup@v1
    with:
      reviewdog_version: latest

  - name: Run pylint, reviewdog, and send output
    run: |
      pylint src/basemodel.py | reviewdog -efm="%f:%l:%c: %m" | curl -X POST -H "Content-Type: application/json" -d @- http://staging.aviator.co/api/signals > server-response.json

  # todo: update to check for 200 response, log response now for testing purposes
  - name: Upload Response Artifact
    uses: actions/upload-artifact@v3
    with:
      name: server-response
      path: server-response.json
